default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    # Ruff version.
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
      - id: ruff-format
        args:
          - --config=pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      # - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
        exclude: docs/CNAME
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-docstring-first
      - id: debug-statements
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # md formatting
  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.17
    hooks:
      - id: mdformat
        args:
          - --number
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout.git
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA.git
    rev: 1.7.1
    hooks:
      - id: nbqa-ruff
        args:
          - --config=pyproject.toml
          - --ignore=F401,F811,F821,D417,T201

  # Pytest
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: bash -c 'if command -v pytest >/dev/null 2>&1; then pytest -vv; else echo "pytest not installed, skipping tests"; fi'
        language: system
        types:
          - python
        pass_filenames: false
        always_run: true
