name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: build exe
        run: |
          cd ./data_generator
          pip install -r requirements.txt pyinstaller
          pyinstaller --onefile gen_data.py
      # Optionally verify that it works (provided that it does not need user interaction)
      - run: ./dist/gen_data.exe
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
