# This workflow finds which files were changed, prints them,
# and runs `pre-commit` on those files.

# Inspired by the sktime library:
# https://github.com/alan-turing-institute/sktime/blob/main/.github/workflows/test.yml

name: Code Quality Check

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
      - release/*

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-latest  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          token: ${{ secrets.GITHUB_TOKEN || secrets.GH_TOKEN }}

      - name: Cache pre-commit dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit

      - name: Run pre-commits
        id: code-quality-check
        uses: pre-commit/action@v3.0.0
