name: "Test Code Review"

on:
  pull_request:
    paths-ignore:
      - "LICENSE"

jobs:
  review:
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-latest  # Uncomment it if you use it on Gitea

    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-3.5-turbo-16k'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
